# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"is_work": "00_data_stuctures.ipynb",
         "get_end_period_block": "00_data_stuctures.ipynb",
         "get_next_period": "02_dahmen.ipynb",
         "ActivityBlock": "00_data_stuctures.ipynb",
         "create_activity_blocks_from_list_or_array": "00_data_stuctures.ipynb",
         "WorkBlock": "00_data_stuctures.ipynb",
         "create_work_blocks_from_activity_blocks": "00_data_stuctures.ipynb",
         "Shift": "00_data_stuctures.ipynb",
         "turn_string_to_activity_number": "00_data_stuctures.ipynb",
         "ShiftSchedule": "00_data_stuctures.ipynb",
         "RuleEvaluationResult": "00_data_stuctures.ipynb",
         "Penalty": "00_data_stuctures.ipynb",
         "evaluate_shift_schedule": "00_data_stuctures.ipynb",
         "get_covered_activity_demands_per_period": "00_data_stuctures.ipynb",
         "get_covered_aggregate_demand_per_period": "00_data_stuctures.ipynb",
         "display_evaluation_results": "00_reporting.ipynb",
         "display_detailed_penalties": "00_reporting.ipynb",
         "plot_activity_block": "00_reporting.ipynb",
         "plot_work_block": "00_reporting.ipynb",
         "plot_shift_schedule": "00_reporting.ipynb",
         "plot_demand_line": "00_reporting.ipynb",
         "plot_aggregate_demand": "00_reporting.ipynb",
         "plot_activity_demands": "00_reporting.ipynb",
         "plot_demands": "00_reporting.ipynb",
         "plot_demands_for_instance": "00_reporting.ipynb",
         "instance_report": "00_reporting.ipynb",
         "instance_solution_report": "00_reporting.ipynb",
         "DemasseyInstance": "01_demassey.ipynb",
         "RuleSet": "02_dahmen.ipynb",
         "DahmenInstance": "02_dahmen.ipynb"}

modules = ["data_structures.py",
           "reporting.py",
           "demassey.py",
           "dahmen.py"]

doc_url = "https://roemeor.github.io/personnel_scheduling/"

git_url = "https://github.com/roemeor/personnel_scheduling/tree/master/"

def custom_doc_links(name): return None
